-- Affiliator KlikUmroh: people who bring travels to subscribe to KlikUmroh (sprint-plan.md, 4 Oct 2026).
-- Platform-level data like staff_users and coupons: no tenant_id. Separate from the travel agent system.

CREATE TABLE IF NOT EXISTS affiliators (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(20) NULL,
    -- Code in the referral link klikumroh.id/?aff=CODE, generated by the system.
    link_code VARCHAR(20) NOT NULL UNIQUE,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    -- Per-affiliator override of the platform commission rates (NULL = platform default).
    first_rate DECIMAL(5,2) NULL,
    renewal_rate DECIMAL(5,2) NULL,
    bank_name VARCHAR(100) NULL,
    bank_account_number VARCHAR(50) NULL,
    bank_account_holder VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_affiliators_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS affiliator_sessions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    affiliator_id BIGINT UNSIGNED NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_affiliator_sessions_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Clicks on the referral link: data for disputes, never changes who earns the commission.
CREATE TABLE IF NOT EXISTS affiliator_clicks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    affiliator_id BIGINT UNSIGNED NOT NULL,
    ip_address VARCHAR(45) NULL,
    clicked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_affiliator_clicks_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE CASCADE,
    INDEX idx_affiliator_clicks_affiliator (affiliator_id, clicked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A travel belongs to one affiliator, set once at signup (coupon wins over link).
ALTER TABLE tenants
    ADD COLUMN affiliator_id BIGINT UNSIGNED NULL,
    ADD COLUMN affiliator_source ENUM('coupon', 'link') NULL,
    ADD COLUMN affiliated_at TIMESTAMP NULL,
    ADD CONSTRAINT fk_tenants_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE SET NULL,
    ADD INDEX idx_tenants_affiliator (affiliator_id);

-- An affiliator's coupon is a normal coupon owned by the affiliator (one active at a time).
ALTER TABLE coupons
    ADD COLUMN affiliator_id BIGINT UNSIGNED NULL,
    ADD CONSTRAINT fk_coupons_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE SET NULL,
    ADD INDEX idx_coupons_affiliator (affiliator_id);

CREATE TABLE IF NOT EXISTS affiliator_payouts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    affiliator_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    status ENUM('pending', 'paid', 'rejected') NOT NULL DEFAULT 'pending',
    bank_name VARCHAR(100) NOT NULL,
    bank_account_number VARCHAR(50) NOT NULL,
    bank_account_holder VARCHAR(255) NOT NULL,
    rejection_reason TEXT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_affiliator_payouts_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE CASCADE,
    CONSTRAINT fk_affiliator_payouts_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES staff_users (id) ON DELETE SET NULL,
    INDEX idx_affiliator_payouts_affiliator (affiliator_id),
    INDEX idx_affiliator_payouts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One commission per approved payment (UNIQUE payment_verification_id), with the rate and base as a snapshot.
CREATE TABLE IF NOT EXISTS affiliator_commissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    affiliator_id BIGINT UNSIGNED NOT NULL,
    tenant_id BIGINT UNSIGNED NOT NULL,
    payment_verification_id BIGINT UNSIGNED NOT NULL,
    kind ENUM('first', 'renewal') NOT NULL,
    base_amount DECIMAL(15,2) NOT NULL,
    rate DECIMAL(5,2) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    -- Held until this moment, then it can be requested for payout.
    available_at TIMESTAMP NOT NULL,
    payout_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_affiliator_commissions_affiliator FOREIGN KEY (affiliator_id) REFERENCES affiliators (id) ON DELETE CASCADE,
    CONSTRAINT fk_affiliator_commissions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_affiliator_commissions_pv FOREIGN KEY (payment_verification_id) REFERENCES payment_verifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_affiliator_commissions_payout FOREIGN KEY (payout_id) REFERENCES affiliator_payouts (id) ON DELETE SET NULL,
    UNIQUE KEY uq_affiliator_commissions_pv (payment_verification_id),
    INDEX idx_affiliator_commissions_affiliator (affiliator_id, available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO platform_settings (`key`, `value`) VALUES
('affiliator_first_rate', '30'),
('affiliator_renewal_rate', '10'),
('affiliator_coupon_discount', '20'),
('affiliator_hold_days', '14'),
('affiliator_min_payout', '100000')
ON DUPLICATE KEY UPDATE `key` = `key`;
