import {
  LayoutDashboard,
  Users,
  Package as PackageIcon,
  Handshake,
  Globe,
  Settings as SettingsIcon,
  Palette,
  Phone,
  ShieldCheck,
  UserCheck,
  Link2,
  CreditCard,
  Clock,
  Wallet,
  Image as ImageIcon,
  Quote,
  HelpCircle,
  Award,
} from 'lucide-react';
import type { MenuItem } from './Sidebar';

export const getStandardMenuItems = (activeId?: string): MenuItem[] => {
  return [
    {
      id: 'dashboard',
      label: 'Dashboard',
      to: '/',
      icon: <LayoutDashboard size={18} />,
      active: activeId === 'dashboard',
    },
    {
      id: 'prospects',
      label: 'Prospek',
      to: '/prospects',
      icon: <Users size={18} />,
      active: activeId === 'prospects',
    },
    {
      id: 'packages',
      label: 'Paket Umroh',
      to: '/packages',
      icon: <PackageIcon size={18} />,
      active: activeId === 'packages',
    },
    {
      id: 'agents',
      label: 'Sistem Agen',
      icon: <Handshake size={18} />,
      active: activeId?.startsWith('agents') || false,
      children: [
        {
          id: 'agents-pending',
          label: 'Persetujuan Agen',
          to: '/agents/pending',
          icon: <Clock size={15} />,
          active: activeId === 'agents-pending',
        },
        {
          id: 'agents-all',
          label: 'Semua Agen',
          to: '/agents/all',
          icon: <Users size={15} />,
          active: activeId === 'agents-all',
        },
        {
          id: 'agents-payouts',
          label: 'Pengajuan Pencairan',
          to: '/agents/payouts',
          icon: <Wallet size={15} />,
          active: activeId === 'agents-payouts',
        },
        {
          id: 'agents-targets',
          label: 'Target & Reward',
          to: '/agents/targets',
          icon: <Award size={15} />,
          active: activeId === 'agents-targets',
        },
      ],
    },
    {
      id: 'website-content',
      label: 'Konten Web',
      icon: <Globe size={18} />,
      active: activeId?.startsWith('content') || false,
      children: [
        {
          id: 'content-banners',
          label: 'Banner Promo',
          to: '/website-content/banners',
          icon: <ImageIcon size={15} />,
          active: activeId === 'content-banners',
        },
        {
          id: 'content-testimonials',
          label: 'Testimoni Jamaah',
          to: '/website-content/testimonials',
          icon: <Quote size={15} />,
          active: activeId === 'content-testimonials',
        },
        {
          id: 'content-faqs',
          label: 'FAQ / Tanya Jawab',
          to: '/website-content/faqs',
          icon: <HelpCircle size={15} />,
          active: activeId === 'content-faqs',
        },
      ],
    },
    {
      id: 'settings',
      label: 'Pengaturan',
      icon: <SettingsIcon size={18} />,
      active: activeId?.startsWith('settings') || false,
      children: [
        {
          id: 'settings-profile',
          label: 'Profil & Branding',
          to: '/settings/profile',
          icon: <Palette size={15} />,
          active: activeId === 'settings-profile',
        },
        {
          id: 'settings-contact',
          label: 'Kontak & Legalitas',
          to: '/settings/contact',
          icon: <Phone size={15} />,
          active: activeId === 'settings-contact',
        },
        {
          id: 'settings-trust',
          label: 'Badge Kepercayaan',
          to: '/settings/trust',
          icon: <ShieldCheck size={15} />,
          active: activeId === 'settings-trust',
        },
        {
          id: 'settings-seo',
          label: 'SEO & GEO Google',
          to: '/settings/seo',
          icon: <Globe size={15} />,
          active: activeId === 'settings-seo',
        },
        {
          id: 'settings-agent',
          label: 'Sistem & Komisi Agen',
          to: '/settings/agent',
          icon: <UserCheck size={15} />,
          active: activeId === 'settings-agent',
        },
        {
          id: 'settings-domain',
          label: 'Domain & Custom Domain',
          to: '/settings/domain',
          icon: <Link2 size={15} />,
          active: activeId === 'settings-domain',
        },
        {
          id: 'settings-team',
          label: 'Tim & Staf Admin',
          to: '/settings/team',
          icon: <Users size={15} />,
          active: activeId === 'settings-team',
        },
        {
          id: 'settings-subscription',
          label: 'Langganan',
          to: '/settings/subscription',
          icon: <CreditCard size={15} />,
          active: activeId === 'settings-subscription',
        },
      ],
    },
  ];
};
